workflows:
  android-release:
    name: Android Release
    max_build_duration: 120
    environment:
      # Codemagic‑cheatsheet ke mutabiq android_signing mein keystore reference dalo  
      android_signing:
        - my_keystore_reference   # yahan apna keystore reference likho jo Codemagic console mein upload kiya hai 0  
      vars:
        # Agar koi public env var chaho define kar sakte ho  
        PACKAGE_NAME: "com.yourcompany.yourapp"  
        JAVA: 11                     # cheatsheet me software versions define kar sakte ho 1  
    scripts:
      - name: Setup Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Release APK
        script: |
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk   # cheatsheet me artifact path ki example bhi aisi di hui hai 2  
    publishing:
      email:
        recipients:
          - aapka-email@example.com
        notify:
          success: true
          failure: true