workflows:
  android-release:
    name: Android Release
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - keystore:
            path: ./app/my-release-key.jks
            keystore_password: $KEYSTORE_PASSWORD
            key_alias: $KEY_ALIAS
            key_password: $KEY_PASSWORD
    scripts:
      - name: Install dependencies
        script: |
          ./gradlew clean
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      
    publishing:
      email:
        recipients:
          - your-email@example.com