workflows:
  android-release:
    name: Android Release
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - keystore_path: keystore.jks
          keystore_password: $KEYSTORE_PASSWORD
          key_alias: $KEY_ALIAS
          key_password: $KEY_PASSWORD

    scripts:
      - name: Clean project
        script: ./gradlew clean

      - name: Build Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com